services:
    api-1:
        build: .
        image: rinha-laravel-octane:latest
        environment:
            APP_ENV: production
            APP_DEBUG: "false"
            LOG_CHANNEL: stderr
            OCTANE_HTTPS: "false"
            # PHP memory limit por processo/worker (não é o limite do container)
            PHP_MEMORY_LIMIT: 128M
        mem_limit: 128m
        cpus: "0.6"
        healthcheck:
            test: [ "CMD", "wget", "-qO-", "http://localhost:8000/health" ]
            interval: 5s
            timeout: 2s
            retries: 10

    api-2:
        build: .
        image: rinha-laravel-octane:latest
        environment:
            APP_ENV: production
            APP_DEBUG: "false"
            LOG_CHANNEL: stderr
            OCTANE_HTTPS: "false"
            PHP_MEMORY_LIMIT: 128M
        mem_limit: 128m
        cpus: "0.6"
        healthcheck:
            test: [ "CMD", "wget", "-qO-", "http://localhost:8000/health" ]
            interval: 5s
            timeout: 2s
            retries: 10

    lb:
        image: nginx:alpine
        depends_on:
            - api-1
            - api-2
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "9999:9999"
        mem_limit: 64m
        cpus: "0.3"
